# Generated by Django 2.1.4 on 2018-12-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('Kind_of_info', models.CharField(max_length=100)),
                ('Criticality', models.CharField(max_length=100)),
            ],
        ),
    ]
